package com.tej.directo.webrtc

enum class HandshakeStage {
    IDLE,
    INITIALIZING_HARDWARE,
    STARTING_DISCOVERY,
    PEER_FOUND,
    NEGOTIATING_LOCAL_SOCKET,
    EXCHANGING_SDP_OFFER,
    EXCHANGING_SDP_ANSWER,
    GATHERING_ICE_CANDIDATES,
    WAITING_FOR_REMOTE_VIDEO,
    LINK_ESTABLISHED,
    RECONNECTING,
    COMPLETED,
    FAILED
}
